swagger: '2.0'
info:
  title: XSS test <script> alert('Intrusion XSS')</script>
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><script> alert('Intrusion XSS')</script>"></form>
