swagger: '2.0'
info:
  title: XSS test <h1>miow</h1>
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><script> alert('Intrusion XSS')</script>"></form>
