swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert('Intrusion XSS')//
info:
  version: "1.0.0"
  title: XSS img test
  description: onload="alert(1)" <img src=http://169.254.169.254/latest/meta-data/ onclick="alert(2)" onerror="alert(3)">
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
